services:
  client:
    #image: jgarcia423/python-orientdb-client
    build: .
    container_name: client
    volumes:
      - ./compartida:/files/export-orientdb
    depends_on:
      orientdb:
        condition: service_healthy

  orientdb:
    image: orientdb:3.0
    container_name: orientdb
    environment:
      - ORIENTDB_ROOT_PASSWORD=root_passwd
    ports:
      - "127.0.0.1:2424:2424"
    healthcheck:
      test: curl --fail http://localhost:2480 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  apache:
    image: httpd:2.4-alpine
    container_name: apache
    ports:
      - 80:80
    volumes:
      - ./compartida:/usr/local/apache2/htdocs
    depends_on:
      orientdb:
        condition: service_healthy

volumes:
  compartida:
