services:
  client:
    build: .
    depends_on:
      orientdb:
        condition: service_healthy

  orientdb:
    image: orientdb:3.0
    environment:
      - ORIENTDB_ROOT_PASSWORD=root_passwd
    ports:
      - "127.0.0.1:2424:2424"
    healthcheck:
      test: curl --fail http://localhost:2480 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
